### ISSUE TITLE
Modern weather cycle resetting

### ISSUE THREAD

**Issue by Mister-16** [telvarost/QuickAdditions-StationAPI#1]
Just a suggestion that I think would go well with the snow above y level feature. Essentially, before 1.18, sleeping would reset the chance that precipitation would occur, so sleeping frequently would effectively stop rain or snow from ever happening. It'd be nice to add this 1.18 feature into the mod if possible. 

Info found on [Reddit](https://www.reddit.com/r/GoldenAgeMinecraft/comments/12ey09a/comment/jfdh71e/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button), confirmed on the minecraft [wiki](https://minecraft.wiki/w/Weather#History).

**Comment by telvarost** [comment]
I took a crack at it. Let me know what you think

**Comment by telvarost** [comment]
Finished. Open up a new ticket if you need anything else with it
